services:
  - type: web
    name: mardongaz
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn sprinter_booking.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "mardongaz.onrender.com"
      - key: PYTHON_VERSION
        value: "3.11.0"
