# Generated by Django 6.0.7 on 2026-07-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('destination_lat', models.FloatField(verbose_name='Широта назначения (Lat)')),
                ('destination_lng', models.FloatField(verbose_name='Долгота назначения (Lng)')),
                ('destination_name', models.CharField(max_length=255, verbose_name='Место назначения (Адрес)')),
                ('booking_date', models.DateField(verbose_name='Дата поездки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
                ('status', models.CharField(choices=[('pending', 'Ожидает (Pending)'), ('confirmed', 'Подтвержден (Confirmed)'), ('completed', 'Завершен (Completed)'), ('cancelled', 'Отменен (Cancelled)')], default='pending', max_length=20, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
